import type { Client, Processor, Product, Quote } from "./types";

const commonSpecs = [
  "Tipo de produto: Painel de LED modular",
  "Vida útil estimada: até 100.000 horas",
  "Sistema de processamento: NovaStar",
  "Fornecedor de solução LED: LED Wave",
  "Operação: uso contínuo",
  "Formato de montagem modular por gabinetes",
];

const cobSpecs = [
  ...commonSpecs,
  "Tecnologia COB",
  "Gabinete 0,60 x 0,33 m",
  "Alta definição para curta distância",
  "Melhor acabamento visual",
  "Proteção superior dos LEDs",
  "Alto contraste e baixo reflexo",
  "Manutenção frontal",
  "Design slim",
];

const gobSpecs = [
  ...commonSpecs,
  "Tecnologia GOB",
  "Gabinete 0,64 x 0,48 m",
  "Proteção superior contra impactos leves",
  "Maior resistência física do módulo",
  "Boa uniformidade de imagem",
  "Alta durabilidade",
  "Manutenção frontal",
];

const smdSpecs = [
  ...commonSpecs,
  "Tecnologia SMD",
  "Gabinete 0,64 x 0,48 m",
  "Boa definição",
  "Excelente custo-benefício",
  "Alta luminosidade",
  "Manutenção acessível",
];

const outdoorSpecs = [
  ...commonSpecs,
  "Tecnologia SMD Outdoor",
  "Alta luminosidade",
  "Resistência climática",
  "Estrutura robusta",
  "Proteção para uso externo",
  "Boa visibilidade em ambientes externos",
];

export const products: Product[] = [
  {
    id: "cob-p12",
    category: "indoor",
    technology: "COB",
    pixelPitch: "P1.2",
    pixelPitchMm: 1.2,
    cabinetSize: "0,60 x 0,33",
    pricePerSqm: 37253.82,
    supplier: "LED Wave",
    processorSystem: "NovaStar",
    lifespanHours: 100000,
    application: "Indoor Ultrawide / Cinema",
    recommendedUse: "Cinema residencial, auditórios premium, salas executivas e ambientes de alto padrão.",
    formats: [
      { width: 2.4, height: 1.02 },
      { width: 3, height: 1.35 },
      { width: 3.6, height: 1.35 },
    ],
    technicalHighlights: cobSpecs,
    commercialDifferentials: [
      "Ideal para projetos em que a qualidade de imagem é prioridade.",
      "Excelente para ambientes sofisticados, salas premium e cinema indoor.",
      "Melhor opção para curta distância de visualização.",
    ],
  },
  {
    id: "cob-p15",
    category: "indoor",
    technology: "COB",
    pixelPitch: "P1.5",
    pixelPitchMm: 1.5,
    cabinetSize: "0,60 x 0,33",
    pricePerSqm: 31622.2,
    supplier: "LED Wave",
    processorSystem: "NovaStar",
    lifespanHours: 100000,
    application: "Indoor Ultrawide / Cinema",
    recommendedUse: "Auditórios, salas de reunião, ambientes internos premium e projetos corporativos.",
    formats: [
      { width: 2.4, height: 1.02 },
      { width: 3, height: 1.35 },
      { width: 3.6, height: 1.35 },
    ],
    technicalHighlights: cobSpecs,
    commercialDifferentials: [
      "Imagem refinada para ambientes internos premium.",
      "Ótimo equilíbrio entre definição, acabamento e investimento.",
    ],
  },
  {
    id: "gob-p15",
    category: "indoor",
    technology: "GOB",
    pixelPitch: "P1.5",
    pixelPitchMm: 1.5,
    cabinetSize: "0,64 x 0,48",
    pricePerSqm: 22169.9,
    supplier: "LED Wave",
    processorSystem: "NovaStar",
    lifespanHours: 100000,
    application: "Indoor Ultrawide / Cinema",
    recommendedUse: "Auditórios, igrejas, ambientes corporativos e áreas de circulação.",
    formats: [
      { width: 3.2, height: 1.44 },
      { width: 3.84, height: 1.44 },
    ],
    technicalHighlights: gobSpecs,
    commercialDifferentials: [
      "Equilibra imagem, resistência e custo-benefício.",
      "Excelente para igrejas, auditórios e áreas com circulação de pessoas.",
      "Mais protegido que painéis SMD tradicionais.",
    ],
  },
  {
    id: "gob-p18",
    category: "indoor",
    technology: "GOB",
    pixelPitch: "P1.8",
    pixelPitchMm: 1.8,
    cabinetSize: "0,64 x 0,48",
    pricePerSqm: 19701.08,
    supplier: "LED Wave",
    processorSystem: "NovaStar",
    lifespanHours: 100000,
    application: "Indoor Ultrawide / Cinema",
    recommendedUse: "Igrejas, lojas, auditórios e ambientes internos com bom custo-benefício.",
    formats: [
      { width: 3.2, height: 1.44 },
      { width: 3.84, height: 1.44 },
    ],
    technicalHighlights: gobSpecs,
    commercialDifferentials: [
      "Boa proteção física para ambientes de fluxo intenso.",
      "Indicado para projetos que precisam de durabilidade e imagem consistente.",
    ],
  },
  {
    id: "smd-p25",
    category: "indoor",
    technology: "SMD",
    pixelPitch: "P2.5",
    pixelPitchMm: 2.5,
    cabinetSize: "0,64 x 0,48",
    pricePerSqm: 11672.9,
    supplier: "LED Wave",
    processorSystem: "NovaStar",
    lifespanHours: 100000,
    application: "Indoor Ultrawide / Cinema",
    recommendedUse: "Ambientes comerciais, igrejas, salões, varejo e comunicação interna.",
    formats: [{ width: 3.84, height: 1.44 }],
    technicalHighlights: smdSpecs,
    commercialDifferentials: [
      "Boa imagem com investimento mais acessível.",
      "Boa escolha para comunicação visual, apresentações, palcos e varejo.",
    ],
  },
  {
    id: "outdoor-p25",
    category: "outdoor",
    technology: "SMD Outdoor",
    pixelPitch: "P2.5",
    pixelPitchMm: 2.5,
    cabinetSize: null,
    pricePerSqm: 19782,
    supplier: "LED Wave",
    processorSystem: "NovaStar",
    lifespanHours: 100000,
    application: "Outdoor",
    recommendedUse: "Fachadas premium, áreas externas com curta distância de visualização e comunicação externa de alta definição.",
    formats: [],
    technicalHighlights: outdoorSpecs,
    commercialDifferentials: [
      "Alta definição para comunicação externa premium.",
      "Projetado para maior brilho, resistência e visibilidade.",
    ],
  },
  {
    id: "outdoor-p29",
    category: "outdoor",
    technology: "SMD Outdoor",
    pixelPitch: "P2.9",
    pixelPitchMm: 2.9,
    cabinetSize: null,
    pricePerSqm: 14728,
    supplier: "LED Wave",
    processorSystem: "NovaStar",
    lifespanHours: 100000,
    application: "Outdoor",
    recommendedUse: "Fachadas, comunicação externa, painéis publicitários e projetos externos premium.",
    formats: [],
    technicalHighlights: outdoorSpecs,
    commercialDifferentials: [
      "Ideal para fachadas e painéis publicitários de impacto.",
      "Bom equilíbrio entre definição, área e investimento.",
    ],
  },
  {
    id: "outdoor-p39",
    category: "outdoor",
    technology: "SMD Outdoor",
    pixelPitch: "P3.9",
    pixelPitchMm: 3.9,
    cabinetSize: null,
    pricePerSqm: 12220.88,
    supplier: "LED Wave",
    processorSystem: "NovaStar",
    lifespanHours: 100000,
    application: "Outdoor",
    recommendedUse: "Outdoors digitais, fachadas comerciais e áreas externas com maior distância de visualização.",
    formats: [],
    technicalHighlights: outdoorSpecs,
    commercialDifferentials: [
      "Indicado para grandes áreas e maior distância de visualização.",
      "Projetos outdoor exigem validação técnica de estrutura, ventilação e resistência climática.",
    ],
  },
];

export const processors: Processor[] = [
  { name: "VC2", brand: "NovaStar", ports: 2, price: 0 },
  { name: "VX400 PRO", brand: "NovaStar", ports: 4, price: 0 },
  { name: "VX600 PRO", brand: "NovaStar", ports: 6, price: 0 },
  { name: "VX800 PRO", brand: "NovaStar", ports: 8, price: 0 },
  { name: "VX1000 PRO", brand: "NovaStar", ports: 10, price: 0 },
  { name: "VX2000 PRO", brand: "NovaStar", ports: 20, price: 0 },
];

export const servicePricing = {
  indoorStructurePerSqm: 1000,
  outdoorStructurePerSqm: 2000,
  installationPerSqm: 600,
};

export const demoClients: Client[] = [
  {
    id: "client-1",
    name: "Igreja Nova Aliança",
    document: "12.345.678/0001-90",
    phone: "(65) 99999-1000",
    email: "compras@novaalianca.com.br",
    city: "Cuiabá",
    state: "MT",
    projectName: "Painel auditório principal",
    installationSite: "Templo sede",
    notes: "Cliente já possui registro comercial ativo.",
    partnerId: "partner-a",
    createdBy: "seller-a",
  },
];

export const demoQuotes: Quote[] = [
  {
    id: "quote-1",
    quoteNumber: "BOR-2026-0142",
    client: demoClients[0],
    createdBy: "seller-a",
    product: products[6],
    width: 4,
    height: 2,
    includeStructure: true,
    includeInstallation: true,
    includeProcessor: true,
    includeFreight: true,
    includeTechnicalVisit: false,
    includeExtendedWarranty: false,
    processorCost: 0,
    freightCost: 2800,
    technicalVisitCost: 0,
    extendedWarrantyCost: 0,
    marginPercent: 12,
    discountPercent: 3,
    status: "negotiation",
    createdAt: "2026-06-14",
  },
];

export const warrantyText =
  "Os painéis de LED Boreal são projetados para operação contínua, alta estabilidade de imagem e longa vida útil. Com vida útil estimada de até 100.000 horas, os equipamentos oferecem excelente desempenho para projetos corporativos, comerciais, auditórios, igrejas, fachadas e ambientes de alto fluxo. A Boreal trabalha com sistema de processamento NovaStar e soluções LED fornecidas pela LED Wave, buscando alto padrão de desempenho, estabilidade e confiabilidade.";
